# Generated by Django 4.0 on 2022-02-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Age_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_details',
            name='Age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
