# Generated by Django 4.0 on 2022-02-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Age_Api', '0002_date_details_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_details',
            name='Age',
        ),
    ]
